server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

operation:
  additionCost: 12
  subtractionCost: 2
  multiplicationCost: 2
  divisionCost: 2
  squareRootCost: 2
  randomStringCost: 2
  randomStringUrl: "https://www.random.org/clients"





