server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

operation.addition.cost: 1.5
operation.subtraction.cost: 1.0
operation.multiplication.cost: 2.0
operation.division.cost: 2.5
operation.square_root.cost: 3.0
operation.random_string.cost: 4.0


