server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB




randomStringUrl: "https://www.random.org/clients"
additionCost: 10
subtractionCost: 10
multiplicationCost: 10
divisionCost: 10
squareRootCost: 10
randomStringCost: 10
